version: '3.9'

services:
  main:
    container_name: main
    hostname: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    ports:
      - 3002:3000
    command: npm run start:dev
    # env_file:
    #   - .env
    networks:
      - maf_net
    depends_on:
      - redis
  redis:
    container_name: redis
    # hostname: redis # not needed default is redis
    image: redis:7.2.4
    ports:
      - 6379:6379
    networks:
      - maf_net
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prom_data:/prometheus
    networks:
      - maf_net
  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    ports:
      - 3001:3001
    restart: unless-stopped
    environment:
      - GF_SERVER_HTTP_PORT=3001
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
    networks:
      - maf_net
networks:
  maf_net:
volumes:
  prom_data: