---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frd-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: dominwong4/frd-app:latest
    argocd-image-updater.argoproj.io/frd-app.update-strategy: digest
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/dominwong4/experiment.git
    targetRevision: main
    path: helm-charts/frd-app-helm-chart
    helm:
      parameters:
        - name: "namespace"
          value: "default"
        - name: "ingressClassName"
          value: "external-ingress-nginx"
        - name: "image.name"
          value: "dominwong4/frd-app"
        - name: "image.tag"
          value: "latest"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
