name: frd-app CI

on:
  push:
    paths:
      - 'frd-app/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      # create .env and fill the value from secrets
      - name: Create .env.local
        run: |
          touch .env.local
          echo "BASE_API_URL=${{ secrets.BASE_API_URL }}" >> .env.local
          echo "NEXT_PUBLIC_BASE_API_URL=${{ secrets.NEXT_PUBLIC_BASE_API_URL }}" >> .env.local
        working-directory: frd-app

      - name: Install Dependencies
        run: npm i
        working-directory: frd-app

      - run: npm ci
        working-directory: frd-app
        
      - run: npm run lint
        working-directory: frd-app
      
      - name: Build
        run: npm run build
        working-directory: frd-app
      
      # - name: Testing
      #   run: npm test
      #   working-directory: frd-app

      - name: Install playwright browsers
        run: npx playwright install --with-deps
        working-directory: frd-app
        
      - name: Testing
        run: npm run test:e2e
        working-directory: frd-app
      
      - name: Build Docker image
        run: |
          docker build -t dominwong4/frd-app:${GITHUB_SHA} .
          docker tag dominwong4/frd-app:${GITHUB_SHA} dominwong4/frd-app:latest
        working-directory: frd-app
      
      - name: Push Docker image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push dominwong4/frd-app:${GITHUB_SHA}
          docker push dominwong4/frd-app:latest
        working-directory: frd-app