name: frd-app CI

on:
  push:
    paths:
      - 'frd-app/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci
        working-directory: frd-app

      - name: Build
        run: npm run build
        working-directory: frd-app